ARG PGHOST
ARG PGPORT
ARG PGUSER
ARG PGPASSWORD
ARG PGDATABASE
ARG MONGODBURI


ENV PGHOST=$PGHOST
ENV PGPORT=$PGPORT
ENV PGUSER=$PGUSER
ENV PGPASSWORD=$PGPASSWORD
ENV PGDATABASE=$PGDATABASE
ENV MONGODBURI=$MONGODBURI

FROM node:latest

WORKDIR /app
COPY package.json package.json
COPY tsconfig.json tsconfig.json
RUN npm install
RUN npm run build
COPY . .
EXPOSE 8080
CMD ["npm", "run", "start:prod"]
